let person={
    "person1":{
    firstName:"Andrew",
    lastName:"Tate",
    age:25,
    gender:"Male"
    },
    "person2":{
    firstName:"Mark",
    lastName:"Zuckerberg",
    age:30,
    gender:"Male"
    },
    "person3":{
    firstName:"Sara",
    lastName:"Johnson",
    age:35,
    gender:"Female"
    },
    "person4":{
    firstName:"Elon",
    lastName:"Musk",
    age:34,
    gender:"Male"
    },
    "person5":{
    firstName:"Jeff",
    lastName:"Bezos",
    age:35,
    gender:"Male"
    },
    "person6":{
    firstName:"Bill",
    lastName:"Gates",
    age:31,
    gender:"Male"
    },
    "person7":{
    firstName:"Emily",
    lastName:"Davis",
    age:32,
    gender:"Female"
    },
    "person8":{
    firstName:"Diane",
    lastName:"Hendricks",
    age:40,
    gender:"Female"
    },
    "person9":{
    firstName:"Thai",
    lastName:"Lee",
    age:39,
    gender:"Female"
    },
    "person10":{
    firstName:"Steve",
    lastName:"Jobs",
    age:45,
    gender:"Male"
    }
}
for(const personId in person){
    const peopleData=person[personId];
    if(peopleData.gender==="Male"){
        console.log(peopleData.firstName)
    }
}